fix: "go get" deprecated if it means "go install"
this is a fix for the CI error I got:

    Run go get github.com/google/go-licenses
    go: go.mod file not found in current directory or any parent directory.
	    'go get' is no longer supported outside a module.
	    To build and install a command, use 'go install' with a version,
	    like 'go install example.com/cmd@latest'
	    For more information, see https://golang.org/doc/go-get-install-deprecation
	    or run 'go help get' or 'go help install'.
    Error: Process completed with exit code 1.